### ISSUE TITLE
VOC-ReID 模型测试

### ISSUE THREAD

**Issue by JieZA** [Xiangyu-CAS/AICity2020-VOC-ReID#25]
您好，我在尝试运行weakly_supervised_crop_aug.py 文件时始终存在以下错误：
/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py:114: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:143.)
  img = torch.from_numpy(pic.transpose((2, 0, 1))).contiguous()
因此我始终无法生成cropped数据集，然后在test阶段一直报错无法找到AICity20_Cropped数据集。请问test可以只使用下载的AICity ReID 或者Simulation数据集吗？我在aicity20.py中更改了query和gallery路径，全部改成了下载的AICity ReID所在路径， 但程序仍然试图访问cropped数据集，麻烦作者大大告诉一下解决方案，谢谢。

**Comment by JieZA** [comment]
当我运行生成cropped数据集的脚本时出现的错误：
Traceback (most recent call last):
  File "tools/aicity20/weakly_supervised_crop_aug.py", line 150, in <module>
    main()
  File "tools/aicity20/weakly_supervised_crop_aug.py", line 140, in main
    results += vis_actmap(model, cfg, train_loader, out_dir)
  File "tools/aicity20/weakly_supervised_crop_aug.py", line 43, in vis_actmap
    for i, batch in enumerate(loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./lib/data/datasets/dataset_loader.py", line 42, in __getitem__
    img = read_image(img_path)
  File "./lib/data/datasets/dataset_loader.py", line 17, in read_image
    raise IOError("{} does not exist".format(img_path))
OSError: /tf/jupyter_implementation/AICity2020-VOC-ReID/vehicle/AIC20_ReID_Cropped/image_train/029563.jpg does not exist

**Comment by Xiangyu-CAS** [comment]
> 您好，我在尝试运行weakly_supervised_crop_aug.py 文件时始终存在以下错误：
> /usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py:114: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:143.)
> img = torch.from_numpy(pic.transpose((2, 0, 1))).contiguous()
> 因此我始终无法生成cropped数据集，然后在test阶段一直报错无法找到AICity20_Cropped数据集。请问test可以只使用下载的AICity ReID 或者Simulation数据集吗？我在aicity20.py中更改了query和gallery路径，全部改成了下载的AICity ReID所在路径， 但程序仍然试图访问cropped数据集，麻烦作者大大告诉一下解决方案，谢谢。

crop testset会提高测试分数，如果不crop，直接把数据源引用原来的AICity20就行。

**Comment by Xiangyu-CAS** [comment]
建议你直接用detectron2或者mask rcnn crop图片吧，当时以为不能用外部模型，就用的这种方法，比直接detection麻烦多了

**Comment by JieZA** [comment]
博士你好，我成功generate cropped dataset并复现了结果，非常棒的工作，感谢你们的贡献!
有一个比较感兴趣的问题，请问你们后来有分析过那些模型很难正确matching 的hard positives 和 hard negatives吗？有没有什么方法可以在结果中区分出易辨别样本easy samples和难辨别样本hard samples。

**Comment by Xiangyu-CAS** [comment]
感谢关注我们的工作 ：），区分easy和hard最直接的指标就是根据样本之间的similarity，如果模型判断两个样本之间距离很近，但GT却不是一类，那这就是hard example，换句话说就是找False Negative和False Positive

**Comment by JieZA** [comment]
感谢回复。如果我没理解错，最终的similarity应该就是那三个distmat文件。还有一点，在生成的track2.txt结果中，有没有什么方法能快速找出那些错误的判断 false positive 和 false negative？我想把这些matching错误的样例提取出来，再仔细研究一下他们所对应的encoding以及和所对应query图片之间的similarity。

**Comment by Xiangyu-CAS** [comment]
嗯，是的，你理解正确。track2.txt是测试集结果，没有GT，所以只能靠可视化去观察query的top-K结果，可以用tools/aicity20/vis_results.py自己看以下那几个错了，然后对应print下sim

**Comment by JieZA** [comment]
The test feature is normalized
using VOC-ReID
using GPU to compute original distance
starting re_ranking
m: 798  n: 100
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,653 reid_baseline.inference INFO: Validation Results
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,667 reid_baseline.inference INFO: mAP: 100.0%
2021-03-25 15:33:26,687 reid_baseline.inference INFO: CMC curve, Rank-1  :100.0%
2021-03-25 15:33:26,687 reid_baseline.inference INFO: CMC curve, Rank-1  :100.0%
2021-03-25 15:33:26,687 reid_baseline.inference INFO: CMC curve, Rank-1  :100.0%
2021-03-25 15:33:26,687 reid_baseline.inference INFO: CMC curve, Rank-1  :100.0%
2021-03-25 15:33:26,687 reid_baseline.inference INFO: CMC curve, Rank-1  :100.0%

请问博士，我突然发现test过程中mAP和rank1 rank5都是100%，这可能是什么原因导致的？

**Comment by Xiangyu-CAS** [comment]
测试集没有GT，pid和camid都是设置为0，所以测试的时候都是一个ID，那准确率自然就是100%了....

**Comment by JieZA** [comment]
感谢大佬回复。还有一个问题：如果想在VeRi数据集上测试，需要重新用/scripts/veri/baseline.sh脚本训练么？我用的aicity20训练出来的模型测试VeRi，精度非常低。

**Comment by Xiangyu-CAS** [comment]
@jiezhang165 主要是数据集差异，ReID的公开数据集数据量都非常小，在单个公开数据集上训练的模型泛化性很差，无法跨域适应其他场景，所以在aicity20上训出来的模型在veri上测试性能很低。使用同源的数据训练，就可以得到很高的结果，或者自己收集百万图像训练，跨域效果就会很好
